name: Deploy to multiple servers

on:
  push:
    branches: [ main ]

jobs:
  deploy-server1:
    runs-on: [self-hosted1]  # uses runner labeled 'self-hosted1'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy code
        run: |
          cd /var/www/assets-management
          if [ -d ".git" ]; then
            git reset --hard
            git pull origin main
          else
            git clone https://github.com/pippintech/assets-management.git .
          fi
          npm install
          export PATH=$PATH:$(npm bin -g)
          sudo pm2 delete titles-server || true
          sudo pm2 start app.js --name "titles-server" --update-env
          sudo pm2 save

  deploy-server2:
    runs-on: [self-hosted2]  # uses runner labeled 'self-hosted2'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy code
        run: |
          cd /var/www/assets-management
          if [ -d ".git" ]; then
            git reset --hard
            git pull origin main
          else
            git clone https://github.com/pippintech/assets-management.git .
          fi
          npm install
          export PATH=$PATH:$(npm bin -g)
          sudo pm2 delete titles-server || true
          sudo pm2 start app.js --name "titles-server" --update-env
          sudo pm2 save
