name: Deploy to GCP VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Mark directory as safe for Git
        run: git config --global --add safe.directory /var/www/assets-management

      - name: Deploy code to VM
        run: |
          echo "📁 Ensuring app directory exists"
          cd /var/www/assets-management

          if [ -d ".git" ]; then
          echo "📥 Pulling latest code"
          git reset --hard
          git pull origin main
          else
          echo "📥 Cloning repository for the first time"
          git clone https://github.com/pippintech/assets-management.git
          fi

          echo "📦 Installing dependencies"
          npm install

      - name: 🚀 Start or Restart PM2 App
  run: |
    cd /var/www/assets-management

    # Ensure npm global binaries are in PATH
    export PATH=$PATH:$(npm bin -g)

    # Install PM2 if not installed
    if ! command -v pm2 >/dev/null 2>&1; then
      echo "PM2 not found. Installing globally..."
      sudo npm install -g pm2
    fi

    echo "🚀 Starting or restarting app"

    # Delete process only if it exists
    if pm2 list | grep -q titles-server; then
      sudo pm2 delete titles-server
    fi

    # Start the app
    sudo pm2 start app.js --name "titles-server" --update-env
    sudo pm2 save

      