name: Deploy to GCP VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure app directory and update repo
        run: |
          echo "📁 Ensuring app directory exists"
          sudo mkdir -p /var/www/assets-management
          cd /var/www/assets-management

          if [ -d ".git" ]; then
            echo "📥 Pulling latest code"
            git reset --hard
            git pull origin main
          else
            echo "📥 Cloning repository for the first time"
            git clone https://x-access-token:${{ secrets.GH_PAT }}@github.com:pippintech/assets-management.git .
          fi

      - name: 📦 Install dependencies
        run: |
          cd /var/www/assets-management
          npm install

      - name: 🚀 Start or Restart PM2 App
        run: |
          cd /var/www/assets-management
          echo "🚀 Starting or restarting app"
          sudo pm2 delete titles-server || true
          sudo pm2 start app.js --name "titles-server" --update-env
          sudo pm2 save
