name: Deploy Node App to GCP MIG

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Debug GitHub OIDC Claims
        run: |
          export ID_TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=google-cloud")
          echo "Raw OIDC Token:"
          echo "$ID_TOKEN" | cut -c1-200
          echo "----"
          echo "Decoded Claims:"
          echo "$ID_TOKEN" | jq -R 'split(".") | .[1] | @base64d | fromjson'

      - id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/432222429753/locations/global/workloadIdentityPools/github-assets-action/providers/github-assets'
          service_account: github-action-assets-deploy@gmapsdevdemoqa.iam.gserviceaccount.com

      - name: Test GCP Auth
        run: |
          gcloud auth list
          gcloud projects describe gmapsdevdemoqa --format="value(projectId)"
